### ISSUE TITLE
InfluxDBClientError: 400 ("error":"partial write: field type conflict)

### ISSUE THREAD

**Issue by supriyopaul** [deep-compute/logagg#75]
**According to [influxdb doc](https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_tutorial/#data-types) :** 
" by default, InfluxDB assumes all numerical field values are floats."
```influx
> INSERT weather,location=us-midwest temperature=82 1465839830100400200
> show field keys from weather
name: weather
fieldKey    fieldType
--------    ---------
temperature float
```

**But [InfluxDBClient module for python](https://github.com/influxdata/influxdb-python):** It does not do the same. 
```python
>>> from influxdb import InfluxDBClient

>>> json_body = [{"measurement": "cpu_load_short","tags": {"host": "server01","region": "us-west"},"time": "2009-11-10T23:00:00Z","fields": {"value": 82}}]

>>> client = InfluxDBClient('localhost', 8086, 'root', 'root', 'example')
>>> client.create_database('example')
>>> client.write_points(json_body)
True
>>> 
```

```bash
[supriyo][05:59 PM][~]$ influx
Connected to http://localhost:8086 version 1.5.0
InfluxDB shell version: 1.5.0
> show databases
name: databases
name
----
_internal
logs
example
> use example
Using database example
> show measurements
name: measurements
name
----
cpu_load_short
> show field keys from cpu_load_short
name: cpu_load_short
fieldKey fieldType
-------- ---------
value    integer
> 
```
![image](https://user-images.githubusercontent.com/33823698/37906578-3d6215e2-3120-11e8-9ab3-8fdc3b6e487d.png)

**Now the concern is what if the programs change the data-types while using the InfluxdbForwarder?** Points won't get written into database...
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 456, in write_points
    tags=tags, protocol=protocol)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 506, in _write_points
    protocol=protocol
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 302, in write
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 263, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"value\" on 
measurement \"test\" is type integer, already exists as type float dropped=1"}

```

**Comment by supriyopaul** [comment]
Used influxdb==5.0.0, did not help.

**Comment by supriyopaul** [comment]
@prashanthellina  should i log an issue in https://github.com/influxdata/influxdb-python or we should handle this ourselevers?

**Comment by prashanthellina** [comment]
@supriyopaul I did some searching about this on InfluxDB site and could not find any  easy workaround. We'll have to look at the capturing these errors and tracking them as logs and metrics so we can alert the dev that something is going wrong. (need to be careful of creating cycles).

**Comment by supriyopaul** [comment]
https://github.com/influxdata/influxdb-python/issues/572
